export const LOAD_WEATHER = 'LOAD_WEATHER';
export const WEATHER_ISLOADING = 'WEATHER_ISLOADING';
export const WEATHER_FAILED = 'WEATHER_FAILED';

export const LOAD_CURRENT_CITY = 'LOAD_CURRENT_CITY';
export const CURRENT_CITY_FAILED = 'CURRENT_CITY_FAILED';
